# Generated by Django 5.2.1 on 2025-06-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_card_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
