# Generated by Django 5.2.1 on 2025-06-04 21:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_card_is_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='is_favourite',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
