# Generated by Django 5.2.1 on 2025-06-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_card_is_favourite_alter_card_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
