services: 
  backend: 
    build: 
      context: ./backend
      dockerfile: Dockerfile
    
    volumes:
     - ./backend:/app

    ports:
     - 8000:8000

    depends_on:
     - ztpai_db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ztpai_db

  ztpai_db: 
    image: postgres:latest
    
    volumes:
     - ./data:/var/lib/postgresql/data/

    healthcheck:
      test: ["CMD", "pg_isready", "-d", "ztpai_db", "-U", "postgres"]
      timeout: 5s
      retries: 5
      start_period: 60s

    ports:
     - 5432:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ztpai_db
     